import Head from "next/head";

import CountryCard from "@/components/CountryCard";
import SearchandFilter from "@/components/SearchandFilter";
import useCountries from "@/hooks/useCountries";
import Loading from "@/components/Loading";

export default function Home() {
  const [isLoading] = useCountries();

  return (
    <>
      <Head>
        <title>Country Finder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SearchandFilter />
        {!isLoading ? <Loading /> : <CountryCard />}
      </main>
    </>
  );
}
